project_id = "yirbjyysvwnqoquelhcm"

[functions.generate-post]
verify_jwt = true

[functions.post-to-threads]
verify_jwt = true

[functions.post-to-linkedin]
verify_jwt = true

[functions.post-to-instagram]
verify_jwt = true

[functions.process-scheduled-posts]
verify_jwt = false